language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
install:
  - "sudo apt-get install libgd2-xpm-dev 2>&1 | tail -n 4"
  - "cpanm --installdeps --force --notest ."
  - "perl ./Build.PL --accept"
script:
    - "./Build test"
notifications:
  irc:
    channels:
      - "irc.freenode.net#bayadev"
    on_success: change
    on_failure: always