language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
env: PERL_CPANM_OPT="--installdeps --notest ."
notifications:
  irc:
    channels:
      - "irc.freenode.net#bayadev"
    on_success: change
    on_failure: always