language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
install:
  - "cpanm --installdeps --notest ."
  - "perl ./Build.PL"
script:
    - "./Build test"
notifications:
  irc:
    channels:
      - "irc.freenode.net#bayadev"
    on_success: change
    on_failure: always