language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - "sudo apt-get install libgd2-xpm-dev 2>&1 | tail -n 4" # for GD
notifications:
  irc:
    channels:
      - "irc.freenode.net#bayadev"
    on_success: change
    on_failure: always